#ifndef OPCODE_H
#define OPCODE_H

#include <cstdint>

enum class Opcode : uint8_t {

    // Cliente → Servidor
    EMPEZAR_MOVER = 1,
    ATACAR = 2,
    MEDITAR = 3,
    RESUCITAR = 4,
    CURAR = 5,
    TOMAR = 6,
    TIRAR = 7,
    EQUIPAR = 8,
    COMPRAR = 9,
    VENDER = 10,
    DEPOSITAR_ITEM = 11,
    DEPOSITAR_ORO = 12,
    RETIRAR_ITEM = 13,
    RETIRAR_ORO  = 14,
    LISTAR  = 15,
    CHAT_GLOBAL = 16,
    CHAT_PRIVADO = 17,

    // Servidor → Cliente
    ESTADO_PERSONAJE = 26,
    POSICION_ENTIDAD = 27,
    ENTIDAD_DESAPARECIO = 28,
    DANIO_RECIBIDO = 29,
    DANIO_PRODUCIDO = 30,
    ESQUIVE = 31,
    MUERTE_ENTIDAD = 32,
    ITEM_EN_SUELO = 33,
    ITEM_DESAPARECIO_SUELO = 34,
    ACTUALIZAR_INVENTARIO = 35,
    ACTUALIZAR_EQUIPAMIENTO = 36,
    MENSAJE_CHAT = 37,
    RESUCITADO = 39,
    LISTA_ITEMS = 40,
    ERROR_ACCION = 41,
    ORO_EN_SUELO = 42,
    ORO_DESAPARECIO_SUELO = 43,
    ESTADO_USUARIO = 44,
    CHEAT = 45,
    DETENER_MOVER = 46,
    CONTENIDO_BANCO = 48,
    COMPRAR_HECHIZO = 49,
    LISTA_HECHIZOS = 50,
    LANZAR_HECHIZO = 51,
    FX_HECHIZO = 52,
    PROYECTIL = 53,
    CAMBIO_MAPA = 54,
    DESEQUIPAR = 55
};

#endif
