#ifndef CODIGO_ERROR_PERSISTENCIA_H
#define CODIGO_ERROR_PERSISTENCIA_H

#include <cstdint>

enum class CodigoErrorPersistencia : uint8_t {
    NO_SE_PUEDE_ABRIR_ARCHIVO = 0,
    NO_SE_PUEDE_ESCRIBIR = 1,
    NO_SE_PUEDE_RENOMBRAR = 2,
    EOF_PREMATURO = 3,
    BYTES_EXTRA = 4,
    MAGIC_INVALIDO = 5,
    VERSION_INCOMPATIBLE = 6,
    DIMENSIONES_INVALIDAS = 7,
    REGISTRO_INVALIDO = 8,
    NPC_DUPLICADO_O_INVALIDO = 9,
    CANTIDAD_EXCEDE_UINT32 = 10,
};

#endif
