#ifndef CODIGO_ERROR_PROTOCOLO_H
#define CODIGO_ERROR_PROTOCOLO_H

#include <cstdint>

enum class CodigoErrorProtocolo : uint8_t {
    
  // Errores de conexion 
    CONEXION_CERRADA_AL_ENVIAR_BYTES,
    CONEXION_CERRADA_AL_RECIBIR_BYTES,

    CONEXION_CERRADA_AL_ENVIAR_UN_BYTE,
    CONEXION_CERRADA_AL_ENVIAR_DOS_BYTES,
    CONEXION_CERRADA_AL_ENVIAR_CUATRO_BYTES,

    CONEXION_CERRADA_AL_RECIBIR_UN_BYTE,
    CONEXION_CERRADA_AL_RECIBIR_DOS_BYTES,
    CONEXION_CERRADA_AL_RECIBIR_CUATRO_BYTES,

    CONEXION_CERRADA_AL_ENVIAR_CADENA,
    CONEXION_CERRADA_AL_RECIBIR_CADENA,

    ENVIO_INCOMPLETO,
    RECEPCION_INCOMPLETA,

    // Errores de protocolo
    OPCODE_CLIENTE_INVALIDO,
    OPCODE_SERVIDOR_INVALIDO,
    OPCODE_DESCONOCIDO,

    CADENA_DEMASIADO_LARGA,
    CADENA_RECIBIDA_SUPERA_MAXIMO,

    CAMPO_INVALIDO,
    DIRECCION_INVALIDA,
    INDICE_ITEM_INVALIDO,
    TIPO_ENTIDAD_INVALIDO,
    ESTADO_ENTIDAD_INVALIDO,
    CODIGO_ERROR_ACCION_INVALIDO,

    
    ERROR_DESCONOCIDO,
};

#endif
